export const colProfile = [
  {
    name: "userId",
    align: "center",
    label: "userId",
    field: (row) => row.userId,
    sortable: true,
  },
  {
    name: "roleId",
    align: "center",
    label: "roleId",
    field: (row) => row.roleId,
    sortable: true,
  },
  {
    name: "name",
    align: "center",
    label: "name",
    field: (row) => row.name,
    sortable: true,
  },
  {
    name: "username",
    align: "center",
    label: "username",
    field: (row) => row.username,
    sortable: true,
  },
  {
    name: "password",
    align: "left",
    label: "Password",
    field: (row) => row.password,
    sortable: true,
  },
  {
    name: "phoneNo",
    align: "left",
    label: "Phone No.",
    field: (row) => row.phoneNo,
    sortable: true,
  },
  {
    name: "email",
    align: "center",
    label: "Email",
    field: (row) => row.email,
    sortable: true,
  },
  {
    name: "height",
    align: "left",
    label: "Height",
    field: (row) => row.height,
    sortable: true,
  },
  {
    name: "weight",
    align: "left",
    label: "Weight",
    field: (row) => row.weight,
    sortable: true,
  },
];

export const rowsProfile = [
  {
    userId: 1,
    roleId: 1,
    name: "Admin",
    username: "Admin",
    password: "Admin123",
    phoneNo: "012-3456789",
    email: "admin@hlg.com",
    height: 156,
    weight: 56,
  },
  {
    userId: 2,
    roleId: 2,
    name: "Ali",
    username: "Ali",
    password: "Ali123",
    phoneNo: "011-9876543",
    email: "ali@gmail.com",
    height: 176,
    weight: 63,
  },
  {
    userId: 3,
    roleId: 2,
    name: "Abu",
    username: "Abu",
    password: "Abu123",
    phoneNo: "013-1029384",
    email: "abu@gmail.com",
    height: 165,
    weight: 53,
  },
];
